### PR TITLE
Add wildfire visualization project

### LINKED ISSUE #113: Add a Fire Research work in projects
Hi @sgpearse 
When you find time, could you please add your fire research visualization work as a project to the website. See under [adding a new project](https://github.com/NCAR/vast/blob/main/CONTRIBUTING.md) in the contributors guide. This would show up under what we do/R&D menu ([example](https://vast.ucar.edu/projects/)). Lemme know if you have any questions. Thank you!

### PR DESCRIPTION
**Pull request by sgpearse**
Adds a project for work on wildfire visualization with VAPOR.  Fixes #113.

### CODE REVIEW

**Review by NihanthCW — APPROVED** [review]

**Review by NihanthCW — CHANGES_REQUESTED** [review]
hi @sgpearse 
Could you add the term and partners field on the top as well? I know that CISL leadership is looking for collaborative projects and this is a great example of that. Thanks!

**Comment by sgpearse** [comment]
@NihanthCW Sure, I'll add 2021-2023 as the term since the NCAR Innovators Cohort spurred this work but it's also ongoing outside of that project.  Do you happen to know what the syntax for the "partners" field is?  I don't see it mentioned on [the contributors guide](https://github.com/NCAR/vast/blob/main/CONTRIBUTING.md) and do not see any other projects that have this field in the repository.

**Comment by NihanthCW** [comment]
> @NihanthCW Sure, I'll add 2021-2023 as the term since the NCAR Innovators Cohort spurred this work but it's also ongoing outside of that project. Do you happen to know what the syntax for the "partners" field is? I don't see it mentioned on [the contributors guide](https://github.com/NCAR/vast/blob/main/CONTRIBUTING.md) and do not see any other projects that have this field in the repository.

You are right. It's not mentioned in the contributors guide. 
So, here's an [example from pythia](https://github.com/NCAR/vast/blob/main/content/projects/pythia.md) if it helps. 
I believe it is not a part of the template but something you can just mention

**Comment by sgpearse** [comment]
Got it, I added NCAR and Northern Arizona University as partners.  Is it worth mentioning names?  There's four NCAR scientists and two NAU researchers who have been a part of this effort.  Or NCAR labs (RAL, ACOM) as well?

**Comment by sgpearse** [comment]
I'm wondering if a footnote like what's below would be appropriate:

> Collaborators: Scott Pearse (NCAR/CISL), Catrin Edgeley (NAU), William Cannon (NAU), Timothy Juliano (NCAR/RAL), Branko Kosovic (NCAR/RAL), Amy De    Castro (NCAR/RAL), Gabriele Pfister (NCAR/ACOM), Rajesh Kumar (NCAR/RAL)

**Comment by NihanthCW** [comment]
> I'm wondering if a footnote like what's below would be appropriate:
> 
> > Collaborators: Scott Pearse (NCAR/CISL), Catrin Edgeley (NAU), William Cannon (NAU), Timothy Juliano (NCAR/RAL), Branko Kosovic (NCAR/RAL), Amy De    Castro (NCAR/RAL), Gabriele Pfister (NCAR/ACOM), Rajesh Kumar (NCAR/RAL)

Looking at other posts, I feel a footnote is not required since None of the personal are mentioned. Having said that, if you feel it is important, I don't mind that addition.

**Review by NihanthCW — APPROVED** [review]

**Pull request merged**
