### PR TITLE
Adding link to SIParCS presentations and GitHub usernames

### PR DESCRIPTION
**Pull request by jukent**
As discussed in #30 

I couldn't find the GitHub username for a few interns: Aashiq Shaikh and Alina Guha. Do you know theirs @NihanthCW and @erogluorhan ?

### CODE REVIEW

**Comment by erogluorhan** [comment]
> As discussed in #30
> 
> I couldn't find the GitHub username for a few interns: Aashiq Shaikh and Alina Guha. Do you know theirs @NihanthCW and @erogluorhan ?

It was [alinejg](https://github.com/alinejg); sorry for the delay!

**Comment by jukent** [comment]
Thanks @erogluorhan no worries!

**Comment by NihanthCW** [comment]
> As discussed in #30
> 
> I couldn't find the GitHub username for a few interns: Aashiq Shaikh and Alina Guha. Do you know theirs @NihanthCW and @erogluorhan ?
 Aashiq's username is aashiqsworld

**Comment by jukent** [comment]
Added both. Thanks!

**Pull request merged**
