### PR TITLE
News blurb about ESDS Apr 17 event on unstructured grids

### PR DESCRIPTION
**Pull request by erogluorhan**
The blurb could take help from additional photos, if any.

@anissa111 @kafitzgerald @philipc2

### CODE REVIEW

**Comment by kafitzgerald** [comment]
This looks good to me.  Unfortunately, I didn't grab any photos from the event.

**Comment by erogluorhan** [comment]
> This looks good to me. Unfortunately, I didn't grab any photos from the event.

Thanks @kafitzgerald ! Feel free to give it a review; I didn't want to ask review from too many of you at first.

**Review by jukent — APPROVED** [review]

**Comment by clyne** [comment]
> 

How about using one from Deepak's blog [post](https://ncar.github.io/esds/blog/), or seeing if Deepak as any others?

**Comment by erogluorhan** [comment]
> > 
> 
> How about using one from Deepak's blog [post](https://ncar.github.io/esds/blog/), or seeing if Deepak as any others?

The one in this PR is already from Deepak's ESDS post, and I think we had only one photo from the event, but let me still double check with Deepak.

I'd suggest we merge this one now, and if any photos from Deepak, I can update the post.

**Review by clyne — APPROVED** [review]
Thanks for putting this together!

**Pull request merged**
